use_frameworks!

platform :ios, '13.0'

target 'HitPaySDK_Example' do
  pod 'HitPaySDK', :path => '../'
#  pod 'HitPaySDK'

  target 'HitPaySDK_Tests' do
    inherit! :search_paths

    
  end
end


#target 'HitPaySDK_Example' do
#  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!
#  pod 'HitPaySDK'
#  # Pods for Alo
#
#end
